- name: Install Jenkins
  hosts: jenkins-server
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name:
          - openjdk-11-jdk
          - wget
          - gnupg

    - name: Add the Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add the Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update package cache after adding Jenkins repository
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes